### Different types of array

In [2]:
import numpy as np

In [9]:
# All 0's matrix
np.zeros(2)
a = np.zeros((3,4))

In [7]:
# All 1's matrix
np.ones(3)
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [10]:
# Any other number (full_like)
np.full_like((a), 5)

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [11]:
# Random decimal number
np.random.rand(4,5)

array([[0.33524662, 0.92576774, 0.97737839, 0.73969593, 0.40067337],
       [0.39033213, 0.95503928, 0.66792729, 0.74832835, 0.85059273],
       [0.22719651, 0.18008313, 0.49716943, 0.80212979, 0.67960008],
       [0.54823977, 0.69390352, 0.6686614 , 0.35687477, 0.08448907]])

In [13]:
# Random decimal number 
np.random.random_sample(a.shape)

array([[0.50573298, 0.06328137, 0.3398444 , 0.14187362],
       [0.22009103, 0.59084863, 0.20212285, 0.79710021],
       [0.71628576, 0.42218409, 0.04928475, 0.39798503]])

In [17]:
# random integer value
np.random.randint(-4,7, size=(3,3))

array([[ 0,  5, -4],
       [ 3, -2,  4],
       [ 4, -4,  3]])

In [18]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
# Array repeat
arr = np.array([[1,2,3]])
a2 = np.repeat(arr, 3, axis=0)
print(a2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [28]:
# Custom array
output = np.ones((5,5))
#print(output)
z = np.zeros((3,3))
z[1,1] = 9
#print(z)
output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Mathematics