# Numpy and Memory

- Numpy uses pass-by-reference semantics so that slice operations are views into the array without implicit copying. 
- In Numpy terminology, *slicing* creates views (not copying) and advance indexing creates copies
- If the indexing object is a non-tuple sequence object, another Numpy array, or a tuple with at least one sequence object or Numpy array, then indexing creates copies

In [1]:
import numpy as np

In [2]:
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
# duplicate last dimension
x[:, [0,1,2,2]]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
# Duplicate last dimension and assing it to y
y = x[:, [0,1,2,2]]
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
# Now Change an element in x
x[0,0] = 9
x # x changed

array([[9., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
# y didn't changed
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

- If we contruct y by slicing then the change will affect y because a view is just a window into the same memory

In [7]:
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# create a view of the upper left piece
y = x[:2, :2]
y

array([[1., 1.],
       [1., 1.]])

In [9]:
# Change the value of x
x[0,0] = 99
x

array([[99.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [10]:
# value of y also changed
y

array([[99.,  1.],
       [ 1.,  1.]])

- If we want to explicitely force a copy without indexing tricks, we can do `y = x.copy()`. 

#### Another Example of advance indexing vs slicing

In [11]:
# Create an array
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
# index by integer list to force copy
b = a[[0,1,2]]
b

array([0, 1, 2])

In [13]:
# create a view using slicing
c = a[:3]
c #b and c have the same value

array([0, 1, 2])

In [14]:
# change an element in a
a[0] = 99

In [15]:
a

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
# b didn't change (unaffected)
b

array([0, 1, 2])

In [17]:
# c changed because it's a view of a
c

array([99,  1,  2])

- Manipulating using views is particularly powerful for signal and image processing algorithm that require overlapping fragments of memory

In [18]:
from numpy.lib.stride_tricks import as_strided
x = np.arange(16, dtype=np.int64)
# create an overlaps entiries
y = as_strided(x, (7,4), (16,8)) 
y

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13],
       [12, 13, 14, 15]], dtype=int64)

In [19]:
# assign 99 in every even position
x[::2] = 99
x

array([99,  1, 99,  3, 99,  5, 99,  7, 99,  9, 99, 11, 99, 13, 99, 15],
      dtype=int64)

In [20]:
# The changes appear because y is a view
y

array([[99,  1, 99,  3],
       [99,  3, 99,  5],
       [99,  5, 99,  7],
       [99,  7, 99,  9],
       [99,  9, 99, 11],
       [99, 11, 99, 13],
       [99, 13, 99, 15]], dtype=int64)