# TensorFlow 2.0 Introduction
### Objectives

- TensorFlow Install and Setup
- Representing Tensors
- Tensor Shape and Rank
- Types of Tensors

In [7]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\Soaib\\anaconda3\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


# Tensors
- "A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)

Tensors are a fundemental apsect of TensorFlow. They are the main objects that are passed around and manipluated throughout the program. Each tensor represents a partialy defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape. 

**Data Types Include**: float32, int32, string and others.

**Shape**: Represents the dimension of data.

*Just like vectors and matrices tensors can have operations applied to them like addition, subtraction, dot product, cross product etc.*

## Creating Tensors
Full list of datatypes can be found to the following guide- 
https://www.tensorflow.org/api_docs/python/tf/dtypes/DType?version=stable

In [11]:
string = tf.Variable('this is a string', tf.string)
print(string)
number = tf.Variable(234, tf.int16)
print(number)
floating_number = tf.Variable(344.54, tf.float64)
print(floating_number)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=234>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=344.54>


**Note:** Since the rank of this tensor is O, it doesn't have any rank.

## Rank/Degree of Tensors
Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a tensor of rank 0, also known as a **scalar.**

Here is the example of some tensors of higher degree/rank-

In [13]:
rank1 = tf.Variable(['test1', 'test2'], tf.string)
rank2 = tf.Variable([['test1', 'test2'], ['test3', 'test4']])

**Note:** To determine the rank of a tensor we can call the following method.

In [42]:
tf.rank(rank1)
tf.rank(rank2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

The rank of a tensor is direclty related to the deepest level of nested lists. In the first example `['test1', 'test2']` is a rank 1 tensor as the deepest level of nesting is 1. Where in the second example `[['test1', 'test2'], ['test3', 'test4']]` is a rank 2 tensor as the deepest level of nesting is 2.

## Shape of a Tensor
The shape of a tensor is simply the number of elements that exist in each dimension. TensorFlow will try to determine the shape of a tensor but sometimes it may be unknown.

In [17]:
rank2.shape

TensorShape([2, 2])

## Changing Shape
The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.

In [32]:
t1 = tf.ones([1,3,3])
t2 = tf.reshape(t1, [3,3,1])
t3 = tf.reshape(t1, [9, -1])

In [33]:
print(t1)
print(t2)
print(t3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 3, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(3, 3, 1), dtype=float32)
tf.Tensor(
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]], shape=(9, 1), dtype=float32)


## Slicing Tensor
The slice operator can be used on tensors to select specific axes or elements.

When we slice or select elements from a tensor, we can use comma seperated values inside the set of square brackets. Each subsequent value refrences a different dimension of the tensor.

Ex: `tensor[dim1, dim2, dim3]`

In [48]:
# Creating a 2D matrix
m = [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11,12,13,14,15],
     [16,17,18,19,20]]
# Creating a tensor with the matrix
tensor = tf.Variable(m, dtype=tf.int32)

print(tf.rank(tensor))
print(tf.shape(tensor))

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([4 5], shape=(2,), dtype=int32)


In [54]:
# Select some different rows and columns from the tensor
three = tensor[0,2]
print(three)

row1 = tensor[0]
print(row1)

col2 = tensor[:, 1]
print(col2)

row2_4 = tensor[1::2]
print(row2_4)

col2_in_row3and4 = tensor[2:4, 1]
print(col2_in_row3and4)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 2  7 12 17], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([12 17], shape=(2,), dtype=int32)


## Types of Tensor
There are diffent types of tensors. The following are the most used tensors-
- Variable
- Constant
- Placeholder
- SparseTensor

With the execption of ```Variable``` all these tensors are immuttable, meaning their value may not change during execution.

For now, it is enough to understand that we use the Variable tensor when we want to potentially change the value of our tensor.
